Repository nanlabs/backend-reference, pull requests merged in 2023-10, with the labels that each got.

#58 Create requirement files for dev and prod
  examples/fastapi-gql/README.md
  examples/fastapi-gql/requirements.dev.txt
  examples/fastapi-gql/requirements.txt
Labels: Hacktoberfest, hacktoberfest-accepted, dependencies

#59 Add requirements file for dev and prod and update Readme file
  examples/fastapi-base/README.md
  examples/fastapi-base/requirements.txt
  examples/fastapi-base/requiremets.dev.txt
Labels: Hacktoberfest, dependencies

#60 Split requiremnts file and update Readme
  examples/fastapi-crud/README.md
  examples/fastapi-crud/requirements.dev.txt
  examples/fastapi-crud/requirements.txt
Labels: Hacktoberfest, hacktoberfest-accepted, dependencies

#68 #54 - Super-linter implementation
  .github/workflows/lint.yml
Labels: Hacktoberfest, hacktoberfest-accepted
